---
- hosts: web-server
  become: yes
  become_method: sudo

  tasks:

  - name: Install pip
    yum:
      update_cache: yes
      name: python3-pip

  - name: Add Docker Repository
    yum_repository:
      repo: https://hub.docker.com/repository/docker/ashish18/flask_python3_application
      state: present

  - name: Update yum and install docker-ce
    yum: update_cache=yes name=docker-ce state=latest

  - name: install docker-py
    pip: name=docker-py

  - name: enable Docker services
    service:
      name: "docker"
      state: started
      enabled: yes

  - name: Check if container is running
    shell: docker ps

  - name: run docker image
    shell: docker run -dit --name flask_python3_application -p 5000:5000 ashish18/flask_python3_application:flask_webapp

  - name: show running images
    shell: docker images
